name: Update File

on:
  workflow_dispatch:
    inputs:
      file-location:
        description: 'Location of the file in the GitHub repository'
        required: true
      username:
        required: true
      branch:
        description: 'Branch to update'
        required: true
      new-content:
        description: 'New content of the file'
        required: true
      repo-url:
        description: 'Enter your repository URL'
        required: true
      token:
        description: 'Enter token'
        required: true

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:

      - name: Update File
        run: |
          FILE_LOCATION=${{ inputs.file-location }}
          BRANCH_NAME=${{ inputs.branch }}
          NEW_CONTENT="${{ inputs.new-content }}"

          # Ensure the branch exists
          git clone https://${{inputs.username}}:${{inputs.token}}@${{inputs.repo-url}}
          git fetch origin ${BRANCH_NAME}:${BRANCH_NAME}
          git checkout ${BRANCH_NAME}

          # Update the file content
          echo "${NEW_CONTENT}" > ${FILE_LOCATION}

          # Commit the changes
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ${FILE_LOCATION}
          git commit -m "Update ${FILE_LOCATION}"

          git push origin ${{inputs.branch}}

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ inputs.branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
